name: http_learn
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  build_runner: ^2.3.3
  http: ^0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
